NewLaminaNumber: Número
NewLaminaTitle: Título
NewLaminaSeccion: Sección
NewLaminasContent: Contenido
NewLamina: Publicar
NoLaminas: Por el momento, no hay laminas.
Laminas: Láminas
MonasHeading: Personas con esta lámina
Informationtext: Información
ReturnToLaminas: Regresar
LaminaTitle numero@Text: Número: #{numero}
OffertTitle: Titulo de oferta
NoMonas: No hay personas ofertando esta mona todavía.
IndiceTablaNumero: Número
IndiceTablaTitulo: Título
IndiceTablaSeccion: Sección
MonaNumber: Lámina número: 
OfertaCreada name@Text: Se agregó la oferta #{name}.
AddOfferHeading: ¿Tienes esta lámina repetida? Agrega una oferta ahora!
AddOfferButton: Agregar
NewOffer: Agregar
PleaseCorrectOffer: Por favor, corrige los errores de la petición.